---
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - pwd
  - ls -la
  - hugo
  - echo "biome.sh" > public/CNAME

deploy:
  - provider: script
    script: sh bin/deploy.sh
    skip_cleanup: true
    on:
      branch: master
