baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Biome"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/biome-sh/biome-website/edit/master/content/"
  description = "Biome"
  author = "Graham Weldon"
  themeVariant = "biome"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true  

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[Languages]
[Languages.en]
title = "Biome"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-wrench'></i> Builder"
identifier = "bldr"
url = "https://bldr.biome.sh"
weight = 9

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/biome-sh"
weight = 10

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-camera'></i> Showcases"
# url = "showcase"
# weight = 11

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "credits"
weight = 30

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
url = "/showcase"
weight = 11

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 30
